
tasks:
  - name: Script Task
    init:  |
      cd /workspace/mob-programming-rpg/webapp
      npm i
    command: |
      pwd
      cd /workspace/mob-programming-rpg/webapp
      npm start
  - name: mob timer
    command: |
      gp preview --external mobti.me/mobrpg
      exit

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - port: 8000-8100
    onOpen: ignore
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-browser

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

vscode:
  extensions:
    - nicoespeon.abracadabra/introduction/getting-started/quickstart
